name: CI

on:
  push:
    branches:
      - main

jobs:
  deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          registry-url: ${{ secrets.NPM_REGISTRY }}
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          registry-url: ${{ secrets.NPM_REGISTRY }}
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Build
        run: npm run build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          registry-url: ${{ secrets.NPM_REGISTRY }}
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Lint
        run: npm run lint

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          registry-url: ${{ secrets.NPM_REGISTRY }}
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Prettier Check
        run: npm run prettier:check

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          registry-url: ${{ secrets.NPM_REGISTRY }}
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Run unit tests
        run: npm run test:unit

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'chore(release):')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 22.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          registry-url: https://registry.npmjs.org/
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Set git user
        run: |
          git config --local user.name \"TrendCapital Robots\"
          git config --local user.email \"tcrobots@yahoo.com\"
      - name: Clean up tags and branches
        run: |
          git tag -l | xargs git tag -d || true
          git fetch --prune --tags
          git branch | grep -v -E '^\\*' | xargs -r git branch -D || true
      - name: Standard Version
        run: npx standard-version --skip.changelog
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --follow-tags
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
